// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfRWppn7_1upu-4ZYMD1y0Futb74lIJtQ',
    appId: '1:803279888682:web:c7efa10fcd597ab9d9fe53',
    messagingSenderId: '803279888682',
    projectId: 'prepnotes-635d6',
    authDomain: 'prepnotes-635d6.firebaseapp.com',
    storageBucket: 'prepnotes-635d6.firebasestorage.app',
    measurementId: 'G-D7FX1VFYHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7be-8WQR0Ea0ipIN5cUoVdd4vToQLBq8',
    appId: '1:803279888682:android:777eac35a2e2bb0fd9fe53',
    messagingSenderId: '803279888682',
    projectId: 'prepnotes-635d6',
    storageBucket: 'prepnotes-635d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABl9Y3xKrYoaWacwSaDn_wlRYsoqGrVvU',
    appId: '1:803279888682:ios:9a99889f7db6728fd9fe53',
    messagingSenderId: '803279888682',
    projectId: 'prepnotes-635d6',
    storageBucket: 'prepnotes-635d6.firebasestorage.app',
    iosClientId: '803279888682-93jmi00s0p6onnsbhejku6ghucgs37cb.apps.googleusercontent.com',
    iosBundleId: 'com.prepnotes.prepnotes',
  );
}
